### ISSUE TITLE
The sample project cannot work on.net 9

### ISSUE THREAD

**Issue by 0use-TE** [indigo-san/ReDocking#18]
I cloned the sample project and can open it, but any operation will cause it to crash. Has this project been abandoned?

Environment:
Window11
Arm64
Visual Studio2022
Dotnet 9

**Comment by yuto-trd** [comment]
@0use-TE You probably tried to launch it using `dotnet run` or the debug button in Visual Studio, but did you see any error messages or stack traces? If nothing was displayed, could you let me know the exit code?

**Comment by 0use-TE** [comment]
![Image](https://github.com/user-attachments/assets/44ff277d-4d62-421c-a8b3-d3e0526bd613)

I'm sorry, I forgot to describe the error. It keeps prompting that a layout loop is detected, ultimately causing the project to freeze. I switched to dotnet8, but this problem still occurs. I look forward to your reply！

**Comment by yuto-trd** [comment]
Thank you for the screenshot.
I also tested it on my Windows 11 (x86_64) environment, and it appears to be working correctly. It seems that the issue might lie with Avalonia, the ARM version of Windows, or some other factor. Unfortunately, I don’t have the physical device, so I can’t verify which one is causing the problem.

**Comment by 0use-TE** [comment]
Image
![Image](https://github.com/user-attachments/assets/86da5698-fd4a-46e7-ae4e-6aa052c3d336)
Viedo
https://github.com/user-attachments/assets/efdfe20d-27fa-4500-be9c-71fc75de98b9
Hello, I have switched the device to the x64 platform, Windows 11. The sidebar is working properly now, but Docking and adding new documents are not functioning. I have debugged this, as shown above.

Clicked to view details：
![Image](https://github.com/user-attachments/assets/5c2dd391-c43b-452f-a992-92a6b7f2b4ea)

**Detailed information：**
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Avalonia.Controls.Primitives.IPopupHost.ConfigurePosition(Avalonia.Visual, Avalonia.Controls.PlacementMode, Avalonia.Point, Avalonia.Controls.Primitives.PopupPositioning.PopupAnchor, Avalonia.Controls.Primitives.PopupPositioning.PopupGravity, Avalonia.Controls.Primitives.PopupPositioning.PopupPositionerConstraintAdjustment, System.Nullable`1<Avalonia.Rect>)'.
  Source=FluentAvalonia
  StackTrace:
   在 FluentAvalonia.UI.Controls.Primitives.TabViewListView.HandleReorder(Point panelPoint)
   在 FluentAvalonia.UI.Controls.Primitives.TabViewListView.OnPointerMoved(PointerEventArgs e)
   在 Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   在 Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   在 Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   在 Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   在 Avalonia.Threading.Dispatcher.Send(SendOrPostCallback action, Object arg, Nullable`1 priority)
   在 Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   在 Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   在 Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   在 FluentAvalonia.Interop.Win32Interop.CallWindowProcW(IntPtr lpPrevWndProc, HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam)
   在 FluentAvalonia.UI.Windowing.Win32WindowManager.WndProc(HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam)
   在 FluentAvalonia.UI.Windowing.Win32WindowManager.WndProcStatic(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   在 Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   在 Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   在 Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   在 Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   在 Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   在 ReDocking.Program.Main(String[] args) 在 D:\StudySoftware\ReDocking\samples\ReDocking.Sample\Program.cs 中: 第 13 行


Thank you sincerely for your response, thank you for your work, I really want to use this library!😀

**Comment by yuto-trd** [comment]
Thank you for the detailed information.
The document tabs ([File 1], [File 2], [File 3]) are currently implemented as a dummy feature using TabViewItem from the FluentAvalonia library.
As a result, clicking the “Add” or “Close” buttons does not trigger any actual behavior.

Looking at the stack trace, it seems that an exception is being thrown when trying to drag a document tab.
This issue appears to be caused by a version mismatch between FluentAvalonia and Avalonia.
I’ve pushed a commit to the main branch with updated versions, so please try it out on your end.

**Comment by 0use-TE** [comment]
@yuto-trd Thank you for your work, it runs successfully on my x64 device. Unfortunately, it still cannot run on ARM, and I am preparing to try reading everyone's source code to fix this problem.😀
